### ISSUE TITLE
DGL: Support CUDA 12

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/dgl-feedstock#1]
Raising to track rebuilding for CUDA 12. More details in issue ( https://github.com/conda-forge/conda-forge.github.io/issues/1963 )

Depends on PyTorch CUDA 12 support ( https://github.com/conda-forge/pytorch-cpu-feedstock/issues/163 )

**Comment by mikemhenry** [comment]
:+1: Cool, feel free to ping me if the pytorch-*-feedstocks need any help!

**Comment by jakirkham** [comment]
PyTorch has been migrated to CUDA 12

Though it looks like the bot is waiting on TensorFlow to be migrated to CUDA 12 as well

Did the bot understand that correctly? Or do we not use TensorFlow with CUDA?

**Comment by mikemhenry** [comment]
We do have a TensorFlow runtime dependency https://github.com/conda-forge/dgl-feedstock/blob/main/recipe/meta.yaml#L95
