### ISSUE TITLE
CMake patch for 1.1.1

### ISSUE THREAD

**Issue by hmacdope** [conda-forge/dgl-feedstock#10]
### Comment:

See attached file for CMake patch for dgl 1.1.1

Probably better to have #3 go in first, didn't want to clutter with a PR until resolved, but here is CMake patch for 1.1.1
We can test how it goes when we want to make a PR.

**Comment by hmacdope** [comment]
[conda-build.patch.txt](https://github.com/conda-forge/dgl-feedstock/files/12375283/conda-build.patch.txt)

**Comment by hmacdope** [comment]
Tagging @mikemhenry

**Comment by mikemhenry** [comment]
Don't worry about the swap file thing, that will take awhile to hash out on conda-smithy, I have been using my fork without any problems/doing it by hand. Go ahead and either commit directly to the bot's PR or make a new one for 1.1.1

**Comment by hmacdope** [comment]
done in #11
