### ISSUE TITLE
Apply swap file fix

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/dgl-feedstock#3]
In order for the builds here to work, this conda-smithy PR ( https://github.com/conda-forge/conda-smithy/pull/1751 ) is needed along with the associated config enabled. Currently builds are failing without that change

This is a known issue. Just documenting for visibility/tracking

**Comment by mikemhenry** [comment]
Swapfile testing here: https://github.com/conda-forge/dgl-feedstock/pull/7

**Comment by jakirkham** [comment]
@conda-forge-admin, please re-render
