### ISSUE TITLE
Kick deployment CI when Azure back up. 

### ISSUE THREAD

**Issue by hmacdope** [conda-forge/dgl-feedstock#47]
@mikemhenry @zklaus Whole of azure seems to be down rn: https://status.dev.azure.com/. We can kick it when its back up.

_Originally posted by @hmacdope in https://github.com/conda-forge/dgl-feedstock/issues/43#issuecomment-2237946480_

**Comment by mikemhenry** [comment]
doing this now, but the error on the PR didn't look like an azure related error

**Comment by mikemhenry** [comment]
build here https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=982695&view=results

**Comment by jakirkham** [comment]
Thanks Mike! 🙏
